### ISSUE TITLE
всмысле где шизик

### ISSUE THREAD

**Issue by crinny** [kumfc/pixel-battle-botnet#2]
мда

**Comment by crinny** [comment]
да ты заебал говнокодер

**Comment by Im-good-person-4-u** [comment]
Ору с вас

**Comment by nm17** [comment]
👀

**Comment by KoLenka12** [comment]
kumfc, я не до конца понял как пользоваться этим ботом. Можно подробно рассказать как этим ботом пользоваться.

**Comment by kumfc** [comment]
@KoLenka12, добавил в ридми

**Comment by KoLenka12** [comment]
@kumfc, а можно запустить бота на винде? Или только на линуксе?

**Comment by kumfc** [comment]
При должном усердии можно в wsl, например.
