### ISSUE TITLE
Слыш а разбор где

### ISSUE THREAD

**Issue by vasilkovivan** [kumfc/pixel-battle-botnet#3]

**Comment by kumfc** [comment]
в плане

**Comment by vasilkovivan** [comment]
В плане разбор кода и чо как работает и куда чо включать

**Comment by kumfc** [comment]
ну там на схемке все понятно

**Comment by LegoChelik** [comment]
Ничего не понятно, конечно, но это мелочи

**Comment by vasilkovivan** [comment]
Плохо понятно, давай понятнее

**Comment by kumfc** [comment]
Ехал Грека через реку.
Видит Грека в реке докер.
Сунул в реку руку Грека.
Докер за руку Греку - цап.
